language: node_js

node_js:
  - "node"  # Current - Latest features
  - "10"    # LTS - Recommended for most users

matrix:
  fast_finish: true

install:
- yarn install

script:
- echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
- if [ "$TRAVIS_NODE_VERSION" == "node" ]; then yarn coverage:publish; fi
- if [ "$TRAVIS_NODE_VERSION" != "node" ]; then yarn test; fi
- yarn lint

deploy:
  - provider: npm
    email: mattias.kindborg@gmail.com
    api_key:
      secure: sDftAEWmbZbPLo2JIULud2Qs0tTNwP0eN3VOyqXuw03PP1HQD9HjdYvcPvqd7/KbaWvt6e4ltWrldBXtv/W81gW9PgUtwAegeHmFm3ZkLZI+iRZX2DbNJKym0+7YedpP3+k2ThjN22tphGaafD3Nb3uJJhAxZpv1HIJHhHMZIR0Q/qWbPl8rMktepfek91A1raoYtFnPCNbmEDQaMjKGHIZN6udJoTH2s2et1bF+bQcgn+NSQ3kyF4btVcOBHeCjdXOC9eQIobyC5NrbI5IugqigogZxIeRHLxfV9b0cnP/J8i+FwQEfmhzu+EP191XZfZOERFwoq7RBg3Hm3GzPHjdB6Xc9U1Ru8nUM9rjs/R+dgiRK//Umd/AP5VDohh9BmsLhqHgbg42nR8C+uHijuH3gG7O5CjPPuG3Aw031tzRefnn0G8ZKLNszcuUGcbeRpUIINvVpBCIUYPWQUTVLcXDFfdCEfxWCoNnkkln2wbuJLfQagJ285sjUVoWRwPoDApSNVnhJxbG4E3JD2YiLTn4eXfrVrV2xaVrsq7RPsPUzQZOHY0AX0/JICwWe+9pnjULTfQ+ibGDCEwggkatl1ZTISI0Pktf9R6fDMqd9PmFNjo44gbMA3kgnJLTspRePICS50sWyW765xo1gMHRdd/IyGfG5ZUBJ16h4BPnChOs=
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    name: Release $TRAVIS_TAG
    api_key:
      secure: D8A4hsEp4xRR7btBEt02t4PJZ+OidLWMEJ7VTKK/vfzQDXfP+COp4BuQJ6cX6CGemnLfptOxp6kS347i5ZGiZt7HAf9IBJTf+QplwuPFdcFYvaJzYFaLNUwvaFpf3mD/+cfpge9pqF8/iDLP8X+7g/X2Oa1NjMjAAGm0u8nx4cfyNcyh17rvd7UOnPMNPgPCP/XNWXGa3JPpwHDGSUg8dDK0oISgt67sRGWfIPjAiE+c5+DWOXRZU4SMj2Jk8V02hXqEYnVBS7mtvsh/FP4tYt8eEmMiU5LlH8hougJvuO6JXUHngISKfxPm7KiYR6pXCvCFKZ2LbpLeGsawb6uLfTEYY7yHLavDyeT6SR5YyWileu+qVEapEbTew5MPY5OvsC9x+Sk/WaYA4/YQDrv/kv0Daxhk4KsNXEbey4WkHieqG5PC5ESfzwetDGf3Iowk7VTq5tzO6GUsOv5VEUoVh8ApZtpdUZ0FseXkIrzm5sbkKA0VpPyIHetB68VP8kC4BJ0Jf7h7q/TVjv4cOc5ComScjzhgWZGae8r4rypyZWCYTJvKfMYnScprO1OA8TeU7WXNJiOo3d9jbeinxaalVoOzd1jLRG6LkJjbNT70CTn7S0JfQDfZ6WMB82QBLIydD9FULyTiizQyxJUgN+WSXhWFuhYKtNIacA7a2AQxjzI=
    on:
      tags: true
