language: node_js

node_js:
  - "node"  # Current - Latest features
  - "6"     # LTS - Recommended for most users
  - "5"
  - "4"

matrix:
  fast_finish: true

install:
  - npm install

script:
  - npm run lint
  