environment:
  matrix:
    - nodejs_version: "4"   # LTS - Recommended for most users
    - nodejs_version: "6"   # Current - Latest features

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - cd ./src
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off